name: Build and Deploy to TestFlight

on:
  push:
    branches:
      - main
    paths:
      - 'ios/**'

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'

    - name: Install CocoaPods dependencies
      run: |
        sudo gem install cocoapods
        pod install --repo-update

    - name: Build iOS App
      run: |
        xcodebuild -workspace YourApp.xcworkspace -scheme YourScheme -sdk iphoneos -configuration Release archive -archivePath $PWD/build/YourApp.xcarchive

    - name: Export Archive
      run: |
        xcodebuild -exportArchive -archivePath $PWD/build/YourApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build

    - name: Install Apple App Store Connect API
      run: gem install spaceship

    - name: Upload to TestFlight
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.API_KEY }}
        ISSUER_ID: ${{ secrets.ISSUER_ID }}
        KEY_ID: ${{ secrets.KEY_ID }}
      run: |
        fastlane pilot upload --api_key_path ./api_key.json --ipa $PWD/build/YourApp.ipa

    - name: Clean Up
      if: always()
      run: rm -rf $PWD/build
