name: iOS Build and Test

on:
  push:
    branches:
      - projectX  # Update this if you are using a different branch
  pull_request:
    branches:
      - projectX  # Update this if you are using a different branch

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'  # Specifying the Xcode version used locally

    - name: Install CocoaPods dependencies
      run: |
        sudo gem install cocoapods
        pod install --repo-update

    - name: Build and Test
      run: |
        xcodebuild -workspace web3authrnexample.xcworkspace -scheme web3authrnexample -sdk iphoneos -configuration Debug build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
